### PR TITLE
RNBS-133::Added support for NZ-BQ DATE_TRUNC/TIME_TRUNC

### PR DESCRIPTION
**Pull request by InderjeetVishnoi**
https://datametica.atlassian.net/browse/RNBS-133

### CODE REVIEW

**Review by soma-mondal — COMMENTED** [review]
Please add test cases.

**Comment by InderjeetVishnoi** [comment]
Test cases added @soma-mondal

**Review by soma-mondal — APPROVED** [review]

**Review by soma-mondal — CHANGES_REQUESTED** [review]
Please add a test case for HOUR and default (if already added for default please ping me the test case
)

**Comment by nosheenSheikh** [comment]
Add test cases for DAY, WEEK, MONTH, QUARTER, YEAR also.

**Comment by nosheenSheikh** [comment]
Add support for the scenario when:
The first operand is timestamp and second operand format string is DAY, WEEK, MONTH, QUARTER, YEAR

**Comment by nosheenSheikh** [comment]
Also write all the possible scenarios and then check what your code is doing and add support for left scenarios.

**Comment by InderjeetVishnoi** [comment]
Hi @nosheenSheikh  , I have added the support for DATETIME_TRUNC along with the test cases.

**Review by soma-mondal — APPROVED** [review]

**Pull request merged**
