### PR TITLE
RAVTDBQ-275/ Mapped IFNULL to NVL in HIVE

### PR DESCRIPTION
**Pull request by rushikeshsapate-dm**
Mapped IFNULL to NVL in HIVE and added test case for the same

### CODE REVIEW

**Comment by Mahesh-Raut** [comment]
L1 done. The changes look good to me.

**Review by Mahesh-Raut — COMMENTED** [review]
L1 done. The changes look good to me.

**Comment by sauajmera** [comment]
changes looks good to me.
L2 completed

**Review by sauajmera — APPROVED** [review]
changes looks good.

**Pull request merged**
