### PR TITLE
RAV-8425

### PR DESCRIPTION
**Pull request by akashshukla-dm**

### CODE REVIEW

**Comment by nosheenSheikh02** [comment]
Looks good to me. Check if all the test cases in `calcite` and `mig` side are passing after this change.

**Comment by soma-mondal** [comment]
Please add test cases.

**Comment by akashshukla-dm** [comment]
> Please add test cases.

Hi Soma, Adding test case in calcite is not possible, because there are dependent changes done in MIg related to this issue.

**Comment by soma-mondal** [comment]
These branch is showing merged as, in another PR #241 these changes were there, and these changes were not reverted properly (revert was done by changing the code with another commit, not by reverting the existing commits). That's why those commits were merged in master, resulting merge of this PR. Kindly create a fresh PR.

**Pull request merged**
